### ISSUE TITLE
What are languages used to create pv?

### ISSUE THREAD

**Issue by JeremieRousseau** [biasmv/pv#107]
hello i am using pv on my web site.

and i have few aks 

i would like to know  if you use python 3.0?
javascript, php, html? What type of file is sh?

I am french, and i am interesting by this type of software.

**Comment by biasmv** [comment]
Hi Jeremie,

most of PV is written in JavaScript (around 15k lines of code). The .sh files you are asking about are simple bash scripts that I use to perform repetitive tasks. There are also a few python scripts in the repository. I'm still more proficient in Python than I am in JavaScript that's why I've chosen to write a few glue  scripts in Python rather than using node.js. If you are starting anew, it's probably best to just stick to JavaScript and not mix all kind of languages together. 

I hope that answers your questions.

Best,
Marco

**Comment by JeremieRousseau** [comment]
yes, thanks for fast answer, i don't know python, i work a little in pure js, in php,  css, i began to read webgl doc, and i know html of course.
