### ISSUE TITLE
List of PV Samples do not work

### ISSUE THREAD

**Issue by mizuchi3** [biasmv/pv#109]
The samples in read the docs are not working, eg:
https://pv.readthedocs.org/en/v1.7.0/sampl
![pv](https://cloud.githubusercontent.com/assets/4498952/8519577/f01c3fb2-23d3-11e5-9401-58834af88071.PNG)
es/structure-with-ligand.html

**Comment by mizuchi3** [comment]
(Firefox38, Chrome43, IE11)

**Comment by biasmv** [comment]
Hi Andrew,

strange. I've tested in all of these browsers (FF38, Chome43, Safari) and don't have the problem you are seeing. I've also cleared the cache and tried if there was anything cached on my machine that accidentally made that work. 

The 404 for modernizr.min.js is caused by the readthedocs.org theme, for some reason they don't seem to properly adjust the path to modernizr.min.js when the documentation file is not in the top-level folder. I've checked in their git repository, and, at least in the newest version, they do seem to properly adjust the path, but I don't know enough of the internals to be sure. 

I've made some changes to the documentation that hopefully will fix these problems. Can you let me know if it's working for you now?

Best,
Marco

**Comment by mizuchi3** [comment]
Hi Marco,

All is fine now, in all browsers !

Andrew
