### ISSUE TITLE
Sticks representation under cursor

### ISSUE THREAD

**Issue by jergosh** [biasmv/pv#167]
Hi Marco,
I was wondering if it's possible to display the residue under cursor as sticks (assuming the rest is displayed as cartoon), similar to your example with highlighting (https://pv.readthedocs.io/en/v1.8.1/sample-hover.html)?

Cheers,
Greg

**Comment by biasmv** [comment]
Hi Greg,

yes, that's possible.I don't have a sample ready for how this can be done, but conceptually it's very similar to the hover sample. Instead of calling colorBy on the existing structure, just create a new object containing just the hovered residue and create a new object. Something like this should work (untested):

```js
function showHoveredResidue(go, atom) {
    var view = go.structure().createEmptyView();
    view.addResidue(atom.residue().full(), true);
    viewer.rm('hovered');
    viewer.cartoon('hovered', view);
}
```

I hope that helps.
